export const BINHDR = {
  DESIGNATOR: 0x80,
  REQUEST_HEADER_SIZE: 10,
  RESPONSE_HEADER_SIZE: 8,
  MAX_COMMANDS_PER_PACK: 127,
  MAX_PAYLOAD_LENGTH: 0x7FFFFFFF,
  SLOT_NO_SLOT: 0xFFFF,
  SLOT_MAX_VALID: 0x3FFF,
  MAX_CLIENT_IDX: 0xFFFF,
  PROTOCOL_ERROR_BIT: 0x80,
  COMMAND_COUNT_MASK: 0x7F,
} as const;

export type BINHDR = typeof BINHDR;
